export const AUTH_FETCH = 'AUTH_FETCH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const TOP_ARTISTS_FETCH_SUCCESS = 'TOP_ARTISTS_FETCH_SUCCESS'
export const TOP_ARTISTS_FETCH_FAIL = 'TOP_ARTISTS_FETCH_FAIL'
export const TOP_ARTISTS_SET_TIME_RANGE = 'TOP_ARTISTS_SET_TIME_RANGE'

export const TOP_HITS_FETCH_SUCCESS = 'TOP_HITS_FETCH_SUCCESS'
export const TOP_HITS_FETCH_FAIL = 'TOP_HITS_FETCH_FAIL'
export const TOP_HITS_SET_TIME_RANGE = 'TOP_HITS_SET_TIME_RANGE'

export const RECENT_TRACKS_FETCH_SUCCESS = 'RECENT_TRACKS_FETCH_SUCCESS'
export const RECENT_TRACKS_FETCH_FAIL = 'RECENT_TRACKS_FETCH_FAIL'