export const AUTH_FETCH = 'AUTH_FETCH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const TOP_ARTISTS_FETCH = 'TOP_ARTISTS_FETCH'
export const TOP_ARTISTS_FETCH_SUCCESS = 'TOP_ARTISTS_FETCH_SUCCESS'
export const TOP_ARTISTS_FETCH_FAIL = 'TOP_ARTISTS_FETCH_FAIL'